package com.system.translationpen.daomaster;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.system.translationpen.exchangerate.bean.ExChangeMultipleItem;
import com.system.translationpen.exchangerate.bean.FirstPageBean;
import com.system.translationpen.settings.bean.FileInfo;
import com.system.translationpen.settings.bean.WifiConnect;

import com.system.translationpen.daomaster.ExChangeMultipleItemDao;
import com.system.translationpen.daomaster.FirstPageBeanDao;
import com.system.translationpen.daomaster.FileInfoDao;
import com.system.translationpen.daomaster.WifiConnectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig exChangeMultipleItemDaoConfig;
    private final DaoConfig firstPageBeanDaoConfig;
    private final DaoConfig fileInfoDaoConfig;
    private final DaoConfig wifiConnectDaoConfig;

    private final ExChangeMultipleItemDao exChangeMultipleItemDao;
    private final FirstPageBeanDao firstPageBeanDao;
    private final FileInfoDao fileInfoDao;
    private final WifiConnectDao wifiConnectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        exChangeMultipleItemDaoConfig = daoConfigMap.get(ExChangeMultipleItemDao.class).clone();
        exChangeMultipleItemDaoConfig.initIdentityScope(type);

        firstPageBeanDaoConfig = daoConfigMap.get(FirstPageBeanDao.class).clone();
        firstPageBeanDaoConfig.initIdentityScope(type);

        fileInfoDaoConfig = daoConfigMap.get(FileInfoDao.class).clone();
        fileInfoDaoConfig.initIdentityScope(type);

        wifiConnectDaoConfig = daoConfigMap.get(WifiConnectDao.class).clone();
        wifiConnectDaoConfig.initIdentityScope(type);

        exChangeMultipleItemDao = new ExChangeMultipleItemDao(exChangeMultipleItemDaoConfig, this);
        firstPageBeanDao = new FirstPageBeanDao(firstPageBeanDaoConfig, this);
        fileInfoDao = new FileInfoDao(fileInfoDaoConfig, this);
        wifiConnectDao = new WifiConnectDao(wifiConnectDaoConfig, this);

        registerDao(ExChangeMultipleItem.class, exChangeMultipleItemDao);
        registerDao(FirstPageBean.class, firstPageBeanDao);
        registerDao(FileInfo.class, fileInfoDao);
        registerDao(WifiConnect.class, wifiConnectDao);
    }
    
    public void clear() {
        exChangeMultipleItemDaoConfig.clearIdentityScope();
        firstPageBeanDaoConfig.clearIdentityScope();
        fileInfoDaoConfig.clearIdentityScope();
        wifiConnectDaoConfig.clearIdentityScope();
    }

    public ExChangeMultipleItemDao getExChangeMultipleItemDao() {
        return exChangeMultipleItemDao;
    }

    public FirstPageBeanDao getFirstPageBeanDao() {
        return firstPageBeanDao;
    }

    public FileInfoDao getFileInfoDao() {
        return fileInfoDao;
    }

    public WifiConnectDao getWifiConnectDao() {
        return wifiConnectDao;
    }

}
